version: "3"
services:
  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers:
            - "host.docker.internal:9092"
            - "host.docker.internal:9093"
          sasl:
            enabled: false
          tls:
            enabled: false
    ports:
      - "8080:8080"